/**
 * Labeled 8004scan fixtures — the exact raw `GET /agents` record shape
 * (`Scan8004Agent`), used by the marketplace verify harness AND future tests.
 *
 * Every fixture is deliberately extreme so the normalize/card mapping honesty
 * rules are observable: verified vs unverified, real zeros vs nulls, mainnet
 * vs testnet, missing names, null health/rank, protocol lists, x402 flags.
 */

import type { Scan8004Agent } from "./types";

/** Realistic EVM agent — verified, BNB Chain, full signals, null ranks (upstream). */
export const EVM_VERIFIED_AGENT: Scan8004Agent = {
  id: "a-1001",
  agent_id: "56:0xCfFacE0003:1001",
  token_id: "1001",
  chain_id: 56,
  chain_type: "evm",
  contract_address: "0xCfFacE0003",
  is_testnet: false,
  owner_id: "u-9",
  owner_address: "0xBb0Aaa9cEf",
  owner_ens: null,
  owner_username: "builder9",
  owner_avatar_url: null,
  owner_publisher_tier: "PRO",
  owner_certified_name: null,
  name: "Grid Hero",
  description: "Automated grid trading bot.",
  image_url: "https://cdn.example/grid-hero.png",
  is_verified: true,
  star_count: 128,
  supported_protocols: ["A2A", "MCP"],
  x402_supported: false,
  total_score: 89,
  rank: null,
  network_rank: null,
  health_score: 95,
  total_feedbacks: 42,
  average_score: 4.6,
  cross_chain_versions: null,
  created_at: "2025-11-02T08:00:00Z",
  updated_at: "2026-01-04T12:30:00Z",
};

/** Solana agent — non-EVM chain type; honest "Chain 101" label fallback. */
export const SOLANA_AGENT: Scan8004Agent = {
  id: "a-1002",
  agent_id: "101:SoLaaV3x:77",
  token_id: "77",
  chain_id: 101,
  chain_type: "solana",
  contract_address: "SoLaaV3x",
  is_testnet: false,
  owner_id: "u-1",
  owner_address: "SoLaaV3xAbc9",
  owner_ens: null,
  owner_username: "solano",
  owner_avatar_url: null,
  owner_publisher_tier: null,
  owner_certified_name: null,
  name: null, // falls back to "Agent #77"
  description: null,
  image_url: null,
  is_verified: false,
  star_count: 3,
  supported_protocols: [],
  x402_supported: true,
  total_score: 60,
  rank: null,
  network_rank: null,
  health_score: null,
  total_feedbacks: 0,
  average_score: 0,
  cross_chain_versions: null,
  created_at: "2025-12-10T09:00:00Z",
  updated_at: "2025-12-28T18:15:00Z",
};

/** Unverified agent with genuine ZERO reputation signals (never hidden). */
export const ZERO_SIGNALS_AGENT: Scan8004Agent = {
  id: "a-1003",
  agent_id: "56:0xZeroScore:42",
  token_id: "42",
  chain_id: 56,
  chain_type: "evm",
  contract_address: "0xZeroScore",
  is_testnet: false,
  owner_id: null,
  owner_address: "0xUnOwNeD",
  owner_ens: null,
  owner_username: null,
  owner_avatar_url: null,
  owner_publisher_tier: null,
  owner_certified_name: null,
  name: "First Steps",
  description: "Freshly listed agent.",
  image_url: null,
  is_verified: false,
  star_count: 0,
  supported_protocols: ["A2A"],
  x402_supported: false,
  total_score: 0,
  rank: null,
  network_rank: null,
  health_score: null,
  total_feedbacks: 0,
  average_score: 0,
  cross_chain_versions: null,
  created_at: "2026-01-20T07:00:00Z",
  updated_at: "2026-01-20T07:00:00Z",
};

/** Testnet (BNB Testnet, chain 97) agent with x402 support declared. */
export const TESTNET_X402_AGENT: Scan8004Agent = {
  id: "a-1004",
  agent_id: "97:0xTe5tNeT:13",
  token_id: "13",
  chain_id: 97,
  chain_type: "evm",
  contract_address: "0xTe5tNeT",
  is_testnet: true,
  owner_id: "u-2",
  owner_address: "0xTe5tOwneR",
  owner_ens: null,
  owner_username: "testnetdev",
  owner_avatar_url: null,
  owner_publisher_tier: null,
  owner_certified_name: null,
  name: "Trading Testbot",
  description: "A testnet agent used for validation.",
  image_url: null,
  is_verified: true,
  star_count: 5,
  supported_protocols: ["MCP", "OASF"],
  x402_supported: true,
  total_score: 71,
  rank: null,
  network_rank: null,
  health_score: 88,
  total_feedbacks: 6,
  average_score: 4.2,
  cross_chain_versions: null,
  created_at: "2025-09-01T00:00:00Z",
  updated_at: "2025-12-01T10:00:00Z",
};

/** X.164: live-seller testnet agent — token 2005 on the marketplace live chain (97). */
export const CANNED_RANGE_KEEPER: Scan8004Agent = {
  id: "a-2005",
  agent_id: "97:0x8004A818BFB912233c491871b3d84c89A494BD9e:2005",
  token_id: "2005",
  chain_id: 97,
  chain_type: "evm",
  contract_address: "0x8004A818BFB912233c491871b3d84c89A494BD9e",
  is_testnet: true,
  owner_id: "u-2005",
  owner_address: "0x0eAc2F4d215A416f891C43BFFa83329Ec249AD5a",
  owner_ens: null,
  owner_username: "rangekeeper",
  owner_avatar_url: null,
  owner_publisher_tier: null,
  owner_certified_name: null,
  name: "Canned Range Keeper",
  description: "ERC-8183 range keeper live seller on BNB Testnet.",
  image_url: null,
  is_verified: true,
  star_count: 9,
  supported_protocols: ["MCP", "OASF"],
  x402_supported: true,
  total_score: 82,
  rank: null,
  network_rank: null,
  health_score: 90,
  total_feedbacks: 7,
  average_score: 4.4,
  cross_chain_versions: null,
  created_at: "2025-10-11T00:00:00Z",
  updated_at: "2025-12-11T10:00:00Z",
};

/** X.164: an unrelated mainnet (chain 56) agent that also happens to have token 2005. */
export const GLYPH_2005: Scan8004Agent = {
  id: "a-glyph-2005",
  agent_id: "56:0xCfFacE0003:2005",
  token_id: "2005",
  chain_id: 56,
  chain_type: "evm",
  contract_address: "0xCfFacE0003",
  is_testnet: false,
  owner_id: "u-glyph",
  owner_address: "0xGlyPhOwner",
  owner_ens: null,
  owner_username: "glyph",
  owner_avatar_url: null,
  owner_publisher_tier: null,
  owner_certified_name: null,
  name: "Glyph #2005",
  description: "A generative glyph agent.",
  image_url: null,
  is_verified: false,
  star_count: 4,
  supported_protocols: ["A2A"],
  x402_supported: false,
  total_score: 40,
  rank: null,
  network_rank: null,
  health_score: 70,
  total_feedbacks: 2,
  average_score: 3.9,
  cross_chain_versions: null,
  created_at: "2025-08-01T00:00:00Z",
  updated_at: "2025-11-01T10:00:00Z",
};
